server:
  port: 8788
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Aa123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8788

mybatis-flex:
  global-config:
    print-sql: true
  #    logic-delete-column: status
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  flex:
    mapper-scan: com.example.demo.mapper # Mapper 扫描路径
app:
  jwt:
    secret: very-very-secret-change-me-to-long-random-string-256bits
    access-token-valid-seconds: 1800   # 30 min
    refresh-token-valid-days: 30